export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_PLANETS_PENDING = 'REQUEST_PLANETS_PENDING';
export const REQUEST_PLANETS_SUCCESS = 'REQUEST_PLANETS_SUCCESS';
export const REQUEST_PLANETS_FAILED = 'REQUEST_PLANETS_FAILED';
